version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: pm_db1
      MYSQL_USER: pm_user
      MYSQL_PASSWORD: '@L0lly122511'
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    image: pm-app:latest
    ports:
      - "8080:80"
    volumes:
      - ./uploads:/var/www/html/uploads
    environment:
      DB_HOST: db
      DB_PORT: '3306'
      DB_USER: pm_user
      DB_PASS: '@L0lly122511'
      DB_NAME: pm_db1
    depends_on:
      db:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

volumes:
  db_data:
    driver: local
